# Generated by Django 5.2.10 on 2026-01-14 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='书名')),
                ('author', models.CharField(max_length=100, verbose_name='作者')),
                ('description', models.TextField(blank=True, null=True, verbose_name='简介')),
                ('cover_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='封面链接')),
                ('publication_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='出版年份')),
                ('isbn', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='ISBN')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '书籍',
                'verbose_name_plural': '书籍',
                'ordering': ['-created_at'],
            },
        ),
    ]
